# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_post_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
